### PR TITLE
Removes duplicated keys in item_field_uri_map.rb

### LINKED ISSUE #192: Duplicate Key Warnings with Ruby 2.2.0
Seems to be an issue related to how Ruby is handling duplicate hash keys.

Output is as follows: 
```ruby
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:25: warning: duplicated key at line 37 ignored: :parent_folder_id
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:34: warning: duplicated key at line 66 ignored: :effective_rights
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:77: warning: duplicated key at line 105 ignored: :is_response_requested
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:103: warning: duplicated key at line 149 ignored: :is_recurring
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:121: warning: duplicated key at line 154 ignored: :recurrence
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:141: warning: duplicated key at line 163 ignored: :companies
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:65: warning: duplicated key at line 167 ignored: :culture
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:26: warning: duplicated key at line 169 ignored: :display_name
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:151: warning: duplicated key at line 181 ignored: :mileage
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:69: warning: duplicated key at line 193 ignored: :conversation_id
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:74: warning: duplicated key at line 194 ignored: :conversation_topic
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:44: warning: duplicated key at line 203 ignored: :categories
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:45: warning: duplicated key at line 207 ignored: :has_attachments
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:27: warning: duplicated key at line 211 ignored: :unread_count
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:43: warning: duplicated key at line 213 ignored: :size
/Users/Austin/.rvm/gems/ruby-2.2.0/gems/viewpoint-1.0.0/lib/ews/types/item_field_uri_map.rb:46: warning: duplicated key at line 217 ignored: :importance
```

May be related to [Ruby Issue 10315](https://bugs.ruby-lang.org/issues/10315).

Would recommend avoiding production use with Ruby 2.2.0 until Viewpoint tests can be run/validated against Ruby 2.2.0.

### PR DESCRIPTION
**Pull request by jwg2s**
Fixes #192.  Lots of warning messages for Ruby 2.2.0.

### CODE REVIEW

**Comment by jwg2s** [comment]
@zenchild let me know what you think here

**Comment by zenchild** [comment]
Good enough for now. That part of the code need some real work anyway. It's been around for quite some time and the field_uri logic could be much better.

Thanks for the PR.

**Comment by martini** [comment]
Thanks for the PR. Current release ist 1.0.0 from June 19, 2014. Any chance to get a new release pushed to public?

**Comment by bmatheny** [comment]
Bump for a new release.

**Comment by gshutler** [comment]
I'll look into doing a release in the coming week, a quick review of [the changes](https://github.com/WinRb/Viewpoint/compare/1.0.0...master) doesn't make it look more than a minor release so should be straightforward.

**Pull request merged**
